apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: ensure-namespace
  namespace: managed
spec:
  remediationAction: enforce
  namespaceSelector:
    include:
      - default
  object-templates:
    - complianceType: musthave
      objectDefinition:
        apiVersion: v1
        kind: Pod
        metadata:
          name: privileged-test
          namespace: default
        spec:
          containers:
            - name: nginx
              image: nginx
              securityContext:
                privileged: true
