apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: template-error-lookup
  namespace: managed
spec:
  remediationAction: inform
  namespaceSelector:
    include:
      - default
  object-templates:
    - complianceType: musthave
      objectDefinition:
        apiVersion: v1
        kind: Pod
        metadata:
          name: |
            {{ lookup "cluster.open-cluster-management.io/v1alpha1" "ClusterClaim" "" "testclaim.open-cluster-management.io".spec.value }}
        spec:
          containers:
            - name: nginx
              image: nginxdd
